import { useContext, useMemo, useState } from "react"
import {
  Activity,
  ArrowRight,
  Bot,
  Brain,
  CheckCircle2,
  Circle,
  FileText,
  Radar,
  Shield,
  Sparkles,
  Target,
} from "lucide-react"
import { useNavigate } from "react-router-dom"
import { UserContext } from "../Contexts/UserContext"

const tools = [
  {
    title: "AI Chat",
    desc: "Ask incident-response and malware-analysis questions in natural language.",
    route: "/dashboard/nextai",
    icon: Brain,
    tags: ["investigate", "assist", "triage"],
  },
  {
    title: "File Scanner",
    desc: "Upload suspicious files and review verdicts generated by backend scanning pipelines.",
    route: "/dashboard/file-scanner",
    icon: FileText,
    tags: ["investigate", "scan", "malware"],
  },
  {
    title: "Threat Intel",
    desc: "Investigate domains, IPs, URLs, and hashes with community sharing workflows.",
    route: "/dashboard/threat-intel",
    icon: Activity,
    tags: ["investigate", "monitor", "ioc"],
  },
  {
    title: "NSFW Detection",
    desc: "Open the real-time moderation stream and monitor model outputs.",
    route: "/dashboard/nsfw",
    icon: Shield,
    tags: ["monitor", "stream", "moderation"],
  },
]

const workModes = [
  {
    key: "investigate",
    label: "Investigate",
    hint: "Trace suspicious indicators and files",
    icon: Radar,
  },
  {
    key: "assist",
    label: "Co-Pilot",
    hint: "Use AI support for incident decisions",
    icon: Bot,
  },
  {
    key: "monitor",
    label: "Monitor",
    hint: "Keep operational streams under watch",
    icon: Target,
  },
]

const Dashboard = () => {
  const navigate = useNavigate()
  const { user } = useContext(UserContext)
  const [activeMode, setActiveMode] = useState("investigate")
  const [tasks, setTasks] = useState([
    { id: 1, title: "Review latest suspicious indicator", done: false },
    { id: 2, title: "Run one file triage scan", done: false },
    { id: 3, title: "Open AI chat for quick guidance", done: true },
  ])

  const displayName = user?.name || user?.username || "Analyst"

  const progress = useMemo(() => {
    const completed = tasks.filter((task) => task.done).length
    const total = tasks.length || 1
    return Math.round((completed / total) * 100)
  }, [tasks])

  const suggestedTools = useMemo(() => {
    return tools.filter((tool) => tool.tags.includes(activeMode)).slice(0, 3)
  }, [activeMode])

  const toggleTask = (taskId) => {
    setTasks((prev) =>
      prev.map((task) => (task.id === taskId ? { ...task, done: !task.done } : task))
    )
  }

  return (
    <div className="w-full min-h-full px-4 md:px-8 py-6 md:py-10 bg-app">
      <div className="max-w-7xl mx-auto space-y-8">
        <section className="mono-panel p-6 md:p-10 grid lg:grid-cols-[1.35fr_1fr] gap-6 md:gap-8">
          <div className="min-w-0">
            <p className="mono-label text-[11px] uppercase text-black/60 dark:text-white/60">Welcome Back</p>
            <h1 className="text-3xl md:text-5xl font-semibold mt-2 tracking-tight break-words">
              Hi {displayName}, ready to secure the stack?
            </h1>
            <p className="max-w-3xl mt-4 text-sm md:text-base text-black/70 dark:text-white/70 leading-relaxed">
              This board adapts to your working mode. Pick a focus area, follow the quick checklist, and jump into
              the most relevant tools without repeating the landing flow.
            </p>

            <div className="mt-6 grid sm:grid-cols-3 gap-2">
              {workModes.map((mode) => {
                const Icon = mode.icon
                const isActive = activeMode === mode.key
                return (
                  <button
                    key={mode.key}
                    onClick={() => setActiveMode(mode.key)}
                    className={`text-left rounded-xl border px-4 py-3 transition ${
                      isActive
                        ? "bg-black text-white border-black dark:bg-white dark:text-black dark:border-white"
                        : "border-black/15 dark:border-white/15"
                    }`}
                  >
                    <div className="inline-flex items-center gap-2">
                      <Icon className="w-4 h-4" />
                      <p className="font-semibold text-sm">{mode.label}</p>
                    </div>
                    <p className={`mt-1 text-xs ${isActive ? "text-white/80 dark:text-black/80" : "text-black/65 dark:text-white/65"}`}>
                      {mode.hint}
                    </p>
                  </button>
                )
              })}
            </div>
          </div>

          <aside className="rounded-2xl border border-black/15 dark:border-white/15 p-4 md:p-5 bg-white/55 dark:bg-white/5">
            <div className="flex items-center justify-between gap-2">
              <p className="font-semibold inline-flex items-center gap-2">
                <Sparkles className="w-4 h-4" />
                Session Checklist
              </p>
              <p className="text-xs text-black/60 dark:text-white/60">{progress}% done</p>
            </div>
            <div className="h-2 mt-3 rounded-full bg-black/10 dark:bg-white/10 overflow-hidden">
              <div className="h-full bg-black dark:bg-white transition-all duration-300" style={{ width: `${progress}%` }} />
            </div>

            <div className="mt-4 space-y-2">
              {tasks.map((task) => (
                <button
                  key={task.id}
                  onClick={() => toggleTask(task.id)}
                  className="w-full text-left rounded-lg border border-black/10 dark:border-white/10 px-3 py-2 inline-flex items-center gap-2"
                >
                  {task.done ? <CheckCircle2 className="w-4 h-4" /> : <Circle className="w-4 h-4" />}
                  <span className={`text-sm ${task.done ? "line-through text-black/55 dark:text-white/55" : ""}`}>{task.title}</span>
                </button>
              ))}
            </div>
          </aside>
        </section>

        <section className="mono-panel p-5 md:p-6">
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div>
              <p className="mono-label text-[11px] uppercase text-black/60 dark:text-white/60">Suggested Next</p>
              <p className="text-xl md:text-2xl font-semibold mt-1 tracking-tight">Tools for {activeMode} mode</p>
            </div>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">
            {suggestedTools.map((tool) => {
              const Icon = tool.icon
              return (
                <button
                  key={`suggested-${tool.title}`}
                  onClick={() => navigate(tool.route)}
                  className="rounded-xl border border-black/15 dark:border-white/15 p-4 text-left hover:border-black dark:hover:border-white transition"
                >
                  <div className="inline-flex items-center gap-2 mb-2">
                    <Icon className="w-4 h-4" />
                    <p className="font-semibold">{tool.title}</p>
                  </div>
                  <p className="text-sm text-black/70 dark:text-white/70">{tool.desc}</p>
                </button>
              )
            })}
          </div>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
          {tools.map((tool) => {
            const Icon = tool.icon
            return (
              <button
                key={tool.title}
                onClick={() => navigate(tool.route)}
                className="mono-panel text-left p-5 group transition duration-300 hover:-translate-y-0.5 hover:border-black dark:hover:border-white"
              >
                <div className="h-10 w-10 rounded-xl border border-black/20 dark:border-white/20 grid place-items-center mb-4 group-hover:bg-black group-hover:text-white dark:group-hover:bg-white dark:group-hover:text-black transition">
                  <Icon className="w-5 h-5" />
                </div>
                <p className="text-lg font-semibold tracking-tight">{tool.title}</p>
                <p className="text-sm mt-2 text-black/70 dark:text-white/70 leading-relaxed">{tool.desc}</p>
                <div className="mt-5 inline-flex items-center gap-2 text-sm font-medium">
                  Open Tool
                  <ArrowRight className="w-4 h-4" />
                </div>
              </button>
            )
          })}
        </section>

        <section className="mono-panel p-6 md:p-8 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <p className="mono-label text-[11px] uppercase text-black/60 dark:text-white/60">Operational posture</p>
            <p className="text-2xl md:text-3xl font-semibold mt-2 tracking-tight">Adaptive. Focused. Analyst-first.</p>
          </div>
          <div className="text-sm text-black/65 dark:text-white/65 max-w-xl">
            Your dashboard now shifts by intent mode and personal session progress, so each login feels active and
            useful instead of repeating a static landing-like screen.
          </div>
        </section>
      </div>
    </div>
  )
}

export default Dashboard
